### ISSUE TITLE
First Character is faded when not scrolling

### ISSUE THREAD

**Issue by fretn** [cbpowell/MarqueeLabel#104]
When the labeltext is short so that there is no scrolling needed, the first character of the label is a bit faded. When I replace the MarqueeLabel with a reqular UILabel this does not happen. 

The first image is the MarqueeLabel, the second one is with an UILabel

![marqueelabel](https://cloud.githubusercontent.com/assets/8073722/7669701/0691fdf0-fc82-11e4-9961-f857bc909870.jpg)
![uilabel](https://cloud.githubusercontent.com/assets/8073722/7669702/06ae04aa-fc82-11e4-9c07-0380da20729a.jpg)

I'm using autolayout with masonry to position the labels inside a uitableviewcell
this is how I create them:

    MarqueeLabel *zoneinfo = [[MarqueeLabel alloc] initWithFrame:dummy duration:8.0 andFadeLength:10.0f];
    zoneinfo.translatesAutoresizingMaskIntoConstraints = NO;
    zoneinfo.textColor = [UIColor colorWithRed:0.8 green:0.8 blue:0.8 alpha:0.9];
    [zoneinfo setFont:[UIFont systemFontOfSize:10]];
    zoneinfo.text = @"VRT Studio"; 
    [cell addSubview:zoneinfo];

    [zoneinfo makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(zonename.top).with.offset(15);
        make.left.equalTo(cell.left).with.offset(0);
        make.width.equalTo(cell.width);
    }];

I'm not sure if it happens when they are scrolling, it's very difficult to see

any ideas ?

**Comment by cbpowell** [comment]
I think you're the first to notice this because most people use larger text! This appears to be due to how CAGradientLayers (maybe just the way I'm using them?) work when you have two color stops at the same point. Basically it looks like it does the opaque —> transparent fade in one pixel.

I've reworked how the fade masking works, so that it animates/adjusts the colors of the stops, rather than the location of the stops. As far as I can tell the effect looks the same. I've pushed it to the [dev branch](https://github.com/cbpowell/MarqueeLabel/tree/dev) so you can check it out. Let me know if it fixes the issue for you - it worked in the test project I set up (using Masonry too).

**Comment by fretn** [comment]
the dev branch fixes this, thanks a lot for the very fast response

**Comment by cbpowell** [comment]
Cool, I'll merge it in and bump the version after a little bit more checking.

**Comment by cbpowell** [comment]
Finally pulled it in to master, in [release 2.2.4](https://github.com/cbpowell/MarqueeLabel/releases/tag/2.2.4). Thanks!
