### ISSUE TITLE
NSParagraphStyle.alignment is not honored

### ISSUE THREAD

**Issue by LeoNatan** [cbpowell/MarqueeLabel#116]
Hello,

When setting a short attributed text to a marquee label, the paragraph style's alignment property is not honored. Could be that other properties aren't honored either.

To reproduce, instead of ```self.demoLabel1.text = @"This label is not as long.";```, set an attributed text with a paragraph style that has `NSTextAlignmnetCenter` alignment.

Thanks

**Comment by cbpowell** [comment]
[These lines](https://github.com/cbpowell/MarqueeLabel/blob/master/MarqueeLabel.m#L316-L317) are the root of the issue. When the text is set to a short, non-scrolling string, MarqueeLabel pulls the value for text alignment (and line break mode) from the value set to super.

Since setting an `attributedString` to MarqueeLabel does not currently also set the super `attributedString` value (necessary to prevent double drawing), the `textAlignment` property just returns the default.

So, I can replicate the issue, but I'm not yet sure how to best solve it without also impacting people who just use normal, non-attributed strings. Unfortunately there's not an easy/surefire way to tell if a UILabel has been set using a normal string or an attributed string, so it might be necessary to keep track manually inside MarqueeLabel. Then these two setting could be switched on that stored stated.

**Comment by LeoNatan** [comment]
I think if you always use the `attributedText` property, you will always get the correct value. So if someone set it the old fashioned way, you will get the correct attributed string nonetheless.

**Comment by LeoNatan** [comment]
Ah, but if you don't call super, the attributed string would not be populated. 

What if you block the double render in the layer level, and then use super?

**Comment by LeoNatan** [comment]
Great, thanks!

**Comment by cbpowell** [comment]
No problem! Good call on blocking drawing at the layer level, that seems to work well.
