### ISSUE TITLE
Scroll performance

### ISSUE THREAD

**Issue by ServusJon** [cbpowell/MarqueeLabel#128]
As already mentioned the scroll perfomance / feel on large text feels not so smooth as excepted.

**Comment by cbpowell** [comment]
Are you seeing poor performance on a device, or on the simulator? If on a device, what type(s)?

On an iPhone 6 with the sample project you provided I see a smooth framerate for the entire scroll, except for right when the animation completes and loops again - I've noted that issue [here in the Swift repo](https://github.com/cbpowell/MarqueeLabel-Swift/issues/22).

**Comment by ServusJon** [comment]
I run it on an iPhone 6 (device). It doesn’t seem to 60 frames per second. Is that possible or is it a illusion?

**Comment by cbpowell** [comment]
Hmm it might be somewhat of an illusion? I profiled your example in Instruments and it seemed to stay at 59/60 fps on my iPhone 6, but if your actual implementation is doing other animations or CPU work it could probably affect it significantly. MarqueeLabel just fires off a CAKeyframeAnimation upon each loop and then does nothing until the next loop, so as far as I know CPU usage is really low most of the time. If you're seeing significant fps drops you might be bumping up against a Core Animation limitation?

Try making the label background a solid, opaque color and setting `fadeLength` to 0.0 if you can, that should give some improvements.

**Comment by ServusJon** [comment]
This makes it a little better. It seems the marqueelabel cuts away some of the characters. Can I remove the limit?

**Comment by cbpowell** [comment]
Which limit are you referring to?

**Comment by ServusJon** [comment]
Character limit

**Comment by cbpowell** [comment]
Oh the size limit that's defined [here](https://github.com/cbpowell/MarqueeLabel-Swift/blob/7e23e84602b4096a3be72c57cab9b6413c202c72/Classes/MarqueeLabel.swift#L649-L650)? Sure, that's there mostly to protect people that aren't aware of the limit, because if you go over the length limit of a UILabel it just doesn't draw anything. I also recently reduced the limit because apparently the 6S limit is lower. If you're not worried about that potential effect or know you won't go over, feel free to comment out that line.

If you're using extremely long strings, that could be a possible reason for your laggy scrolling. Could be pushing Core Animation too far?

**Comment by ServusJon** [comment]
the lagging is also on short labels. i only discovered the truncating when i used a very longlabel. what is the characterlimit?

**Comment by cbpowell** [comment]
There isn't a character count limit, only a size limit. The size limit is fairly big (see the link in my previous comment).

**Comment by JW97** [comment]
#141 I've tweaked the applyGradientMask... method to have some caching/performance improvements. Seemed to somewhat improve the scrolling performance in an app I'm working on

**Comment by cbpowell** [comment]
Guess I'll go ahead and consider this resolved, with no other noted issues and #141 incorporated. I can reopen if otherwise!
