### ISSUE TITLE
FadeLength does not work anymore!

### ISSUE THREAD

**Issue by Foddy** [cbpowell/MarqueeLabel#146]
When I try to enable MarqueeLabel via the StoryBoard mode with this configuration my label disappears if the content should scroll (when I compile the app).

I found out that it must be an error with the FadeLength setting. When I remove this value everything works like expected but without fading. Is there any workaround or am I doing something wrong?

![FadeLength Setting Error](https://cloud.githubusercontent.com/assets/5302050/16595703/dc330d9a-42f0-11e6-9b32-8c4804435d23.png)

**Comment by cbpowell** [comment]
Hmm weird - I'll check it out. It looks like you're using the Objective-C version? I just recently updated the ObjC code to match how edge fades work on the Swift side, and there might be a bug.

What happens if you try setting `fadeLength` in code? (if its easy to try)

**Comment by alpi** [comment]
I have the same issue (using the swift version via Cocoapods and setting everything up in code). Had to set the fadeLength to 0 for now until i have time to look into it.

**Comment by cbpowell** [comment]
Interesting, might be related to the changes in PR #141, assuming you're using release 2.7.6? If so, you could try rolling back to release 2.7.5 and see if the problem goes away.

**Comment by alpi** [comment]
tried downgrading until 2.7.1 and it seems to be still present (even with 2.7.1): the label fades completely away.

**Comment by cbpowell** [comment]
Just to be sure, is this happening with iOS 9 or the iOS 10 betas?

**Comment by alpi** [comment]
tvOS 9 in my case. Here's an example project: [MarqueeTest.zip](https://github.com/cbpowell/MarqueeLabel/files/355697/MarqueeTest.zip)

**Comment by cbpowell** [comment]
So it turns out the issue was that the `gradientMask` layer bounds weren't being updated when the view's bounds changed. I missed that (pretty likely) scenario when doing optimization of the gradient masking awhile back in the Swift version, and then it just recently made it over to the Objective-C side.

In your case, you initialized the MarqueeLabel instance with `CGRectZero` and the gradient mask stop points were calculated right then with a zero-width size. When your layout constraints were later added, the view was of course resized but the gradient mask wasn't subsequently updated.

Thanks a bunch for pointing it out and following up with the example project!

**Comment by goodstechinc** [comment]
Is this updated in version 2.8 on cocoapods? I'm experiencing a similar problem.
