### ISSUE TITLE
Nullable from incompatible type

### ISSUE THREAD

**Issue by alfio86** [cbpowell/MarqueeLabel#159]
Hi,

In my project in iOS 10 (in objective.c version) I found this alert:
Assigning to 'id<CAAnimationDelegate> _Nullable' from incompatible type 'MarqueeLabel *const __strong'
Also in the demo project I find these alerts:
<img width="1135" alt="screen" src="https://cloud.githubusercontent.com/assets/14003895/18507358/48a2476e-7a70-11e6-8a6c-bb1948d3cdae.png">
any suggestions?

Thanks

**Comment by cbpowell** [comment]
Hi - that's because as of the iOS 10.0 SDK, objects set to the `delegate` property on CAAnimations should conform to the `CAAnimationDelegate` protocol. Prior to iOS 10.0 `CAAnimationDelegate` wasn't actually a formally defined protocol.

You should be able to safely ignore these warnings for now, but I'll make a change to get rid of them. To prevent issues for people not yet using the 10.0 SDK, I'll use the [solution seen here](https://github.com/facebook/Shimmer/commit/1130a2da95a04f9f0bf8e4b3174fd4068d3c2cba).
