### ISSUE TITLE
IBDesignables Errors

### ISSUE THREAD

**Issue by meliuxudong** [cbpowell/MarqueeLabel#165]
DDMarketing.storyboard: error: IB Designables: Failed to render and update auto layout status for DDMarketingSelectAreaViewController (fFe-Ma-iYV): Failed to load designables from path (null)

DDMarketing.storyboard: error: IB Designables: Failed to update auto layout status: Failed to load designables from path (null)

But does not affect use

**Comment by iMoreApps** [comment]
+1

**Comment by cbpowell** [comment]
I've had issues with the IBDesignable stuff failing myself too, but I've never really been able to figure it out. I also don't remember what I've used to get it to clear…typically what I was getting didn't prevent a successful build, though. 

Doing a bit of searching on the 2nd of your particular errors, maybe [adding `use_frameworks!` to your podfile](http://stackoverflow.com/questions/28391112/interface-builder-failed-to-load-designables-from-path-null) if you aren't already?

**Comment by eilianlove** [comment]
I also have the same issue. If I change anything in xib, Xcode will build for IB designables whick make me crazy, because it is too slow when build.
```
error: 
 Type 'Int' has no member 'MLContinuous'
code: 
#if TARGET_INTERFACE_BUILDER
@property (nonatomic, assign) IBInspectable NSInteger marqueeType;
#else
@property (nonatomic, assign) MarqueeType marqueeType;
#endif
```

**Comment by cbpowell** [comment]
I realized the demo has a lot of issues with IBDesignables, I think because there are several classes named "MarqueeLabel" for both Swift and Obj-C in the same project.

But I tried a few things which seemed to clear up the similar issues:

1. It might be a pain, but change all your MarqueeLabel instances in Interface Builder back to just regular UILabels (by deleting/clearing the Class field in IB)

2. Clear all the IBDesignable values, easily done by deleting all the User Defined Runtime Attributes. Make a note of them if you need, for Step XX.

3. May or may not be necessary, but Clean your project and delete the Derived Data folder.

4. Quit Xcode.

5. Reopen Xcode, and set the Class field back to MarqueeLabel on all your labels. The Module field should either be the default grey `Current - [Your project name here]` OR `MarqueeLabel` as seen here, in a brand new, Cocoapods-based test project I created: 
<img width="258" alt="screen shot 2016-10-23 at 10 00 49 am" src="https://cloud.githubusercontent.com/assets/593953/19627997/0188399e-9909-11e6-962e-3a075f298707.png">
It should NOT be 'None'.

**Comment by philhudson91** [comment]
Thank you @cbpowell the above fixed worked for me!

**Comment by cbpowell** [comment]
Awesome, I think I'll consider this closed unless anyone is still having issues!

**Comment by orenk86** [comment]
Hi @cbpowell - The solution you wrote won't work for me. I'm still getting the error...

**Comment by AlexisBarat** [comment]
Same here ! XCode 8.2.1

**Comment by nihilenz** [comment]
I'm not using CocoaPods, above suggestions don't help, any help?

**Comment by cbpowell** [comment]
That's interesting, I had tried doing something similar with the demo project with some success. I was thinking the demo project has too many classes called "MarqueeLabel" (the Obj-C one and the Swift one), and IB was getting confused. @nihilenz is only the Obj-C code in your project?

**Comment by chiragDJ22** [comment]
yes i have only Obj-C in my project and also same issue like @alexisbar

**Comment by NateFuller** [comment]
Proposed solution is not working for me either. For step 1 should we also delete any IBOutlets we've setup in our source code? Or should we just modify the IBOutlet to be of type UILabel?

**Comment by cbpowell** [comment]
@NateFuller I think when I did it I just changed the class field? I don't believe I had to delete the IBOutlet itself - of course, success may vary.

**Comment by cbpowell** [comment]
I'm having trouble reproducing this, and I'm thinking it's probably because I'm not using MarqueeLabel as a Pod? [This Stackoverflow thread](http://stackoverflow.com/questions/28204108/ib-designables-failed-to-update-auto-layout-status-failed-to-load-designables) has a fair amount of discussion. It seems to range between it being an Xcode issue and a Cocoapods issue, but nobody has much success. I'm not sure what else I can do in MarqueeLabel to work around the issue.

Per the top answer, make sure you've [updated to the latest version Cocoapods gem](https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods), and it might fix it?

The solution from @nihilenz might be a good/easy stopgap, or the classic quit and restart Xcode, clear derived data, etc., solution.

**Comment by orenk86** [comment]
Removing the library from the podfile and adding the source files manually to the project solved the issue for me...

**Comment by cbpowell** [comment]
It would appear the issue may be related to using MarqueeLabel as a static vs. dynamic framework, as noted in several other issues: https://github.com/CocoaPods/CocoaPods/issues/2792, https://github.com/TTTAttributedLabel/TTTAttributedLabel/issues/460, and https://github.com/glaszig/SZTextView/issues/52.

If you're targeting iOS 7.0, you may not have any option other to add the MarqueeLabel source files manually.

If you're targeting iOS 8.0+, you can:
- Use MarqueeLabel as a dynamic framework using CocoaPods with use_frameworks! in your Podfile
- Use Carthage
- Add the MarqueeLabel source files manually

Taking a page from TTTAttributedLabel, I've added a [note about the issue to the README](https://github.com/cbpowell/MarqueeLabel#ibdesignables).

Will of course update if anything changes to allow other/better workarounds!

**Comment by systemed** [comment]
I was still having this problem with Swift in the latest version, even with `use_frameworks!`. Making a subclass as per @nihilenz's suggestion worked for me:

````
import MarqueeLabel

class Marquee: MarqueeLabel {
}
````
