### ISSUE TITLE
simple example not work

### ISSUE THREAD

**Issue by Nathan187** [cbpowell/MarqueeLabel#166]
does anyone have a simple hello world example?  i'm using a storyboard , following the directions...but the code is failing at "lblTicker.type = .continuous" (exec_bad_access)

i used carthage to get the necessary files/framework...and i'm not building my ui from the code...i'm using storyboards.

**Comment by cbpowell** [comment]
Have you tried the repo's built-in demo project? You'll need to clone the repo separately though, rather than using Carthage.

Based on your EXEC_BAD_ACCESS error, you probably haven't set MarqueeLabel as the class for your `lblTicker` label in Interface Builder. You'll need to change it from the default UILabel type to MarqueeLabel.

**Comment by nboyd-sportdx** [comment]
i have done that.  i tried using carthage and i tried not using it.  i did set the class of the label to MarqueeLabel.  why was this closed so fast?

**Comment by nboyd-sportdx** [comment]
repo's built in project works fine

**Comment by nboyd-sportdx** [comment]
remove carthage framework...added swift file...(in new hello world test project)
works fine...please close
