### ISSUE TITLE
Adjusting spacing between end and beginning of text

### ISSUE THREAD

**Issue by btc** [cbpowell/MarqueeLabel#173]
Hi. Thanks for this library. It's quite helpful.

I was wondering whether it's possible to adjust the spacing between the end and beginning of the text in the label. Right now, the end touches the beginning. Please see photo.

<img width="477" alt="pasted_image_1_3_17__10_08_am" src="https://cloud.githubusercontent.com/assets/734339/21617818/cd28afae-d19c-11e6-8658-fa6684999cc9.png">

**Comment by cbpowell** [comment]
Glad you find it useful!

Totally possible - check out the [`leadingBuffer`](https://github.com/cbpowell/MarqueeLabel/blob/master/Sources/Swift/MarqueeLabel.swift#L240) and/or [`trailingBuffer`](https://github.com/cbpowell/MarqueeLabel/blob/master/Sources/Swift/MarqueeLabel.swift#L264) properties. `leadingBuffer` will offset the beginning of your text (e.g. it's like adding spaces as a prefix on your text string), while `trailingBuffer` adds an empty space at the end of your text (e.g. like adding spaces as a suffix).

The [example GIF of the demo project](https://raw.githubusercontent.com/cbpowell/MarqueeLabel/master/MarqueeLabelDemo.gif) actually illustrates both as well: the first label has a `leadingBuffer`, and the last/sixth label has `trailingBuffer`.

From looking at your photo, I'm guessing you'll probably want to use the `trailingBuffer` property so that your text isn't shifted to the right at the "home"/stopped position - but play around to figure out which you want. Hope this helps!

**Comment by btc** [comment]
Thanks

**Comment by isaranjha** [comment]
From what I'm experiencing, it isn't possible to use trailingBuffer if there is a fadeLength as the label defaults to having a minimum buffer of at least the fadeLength. How can I have a fadeLength of say, 40, but then a trailingBuffer of 0?
