### ISSUE TITLE
Compiler warning 'id<CAAnimationDelegate> incompatible type MarqueeLabel' (Semantic issue)

### ISSUE THREAD

**Issue by averello** [cbpowell/MarqueeLabel#180]
As we have very strict compiler warnings,
could you please fix the following compiler warnings:

`Pods/MarqueeLabel/Sources/ObjC/MarqueeLabel.m:775:33: Assigning to 'id<CAAnimationDelegate> _Nullable' from incompatible type 'MarqueeLabel *const __strong'`

`Pods/MarqueeLabel/Sources/ObjC/MarqueeLabel.m:959:24: Assigning to 'id<CAAnimationDelegate> _Nullable' from incompatible type 'MarqueeLabel *const __strong'`

Thank you

a screenshot
![screen shot 2017-04-21 at 10 46 26](https://cloud.githubusercontent.com/assets/300205/25268090/13763c0a-2680-11e7-930b-8d9aae20b170.png)

**Comment by cbpowell** [comment]
I've changed the Objective-C class to conform to CAAnimationDelegate in [release 3.0.3](https://github.com/cbpowell/MarqueeLabel/releases/tag/3.0.3). In the past I hadn't because Cocoapods would error out since CAAnimationDelegate wasn't actually a declared protocol until iOS 10.0. It seems it builds fine during linting now.

And in the future, you're always welcome to submit pull requests for changes you'd like to see implemented, particularly when it's something specific to your setup!
