### ISSUE TITLE
when label length is chinese and too large, text will invisible

### ISSUE THREAD

**Issue by CrazyDavis** [cbpowell/MarqueeLabel#198]
when the text is chinese and to large, text will invisible

ex: 
let s = "我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我我"

**Comment by cbpowell** [comment]
I haven't had a chance to try your specific text, but with English (Latin) characters I do know that beyond a certain length string the underlying UILabel class will simply stop drawing. MarqueeLabel attempts to [prevent this from happening](https://github.com/cbpowell/MarqueeLabel/blob/d40d160fd10dc5a4177895328259a23c16cacdee/Sources/Swift/MarqueeLabel.swift#L720-L726) by capping the size of the label, but I'm not sure that this check alone is 100% successful.

MarqueeLabel doesn't attempt to work around this, because 1) it's a limitation of UIKit's UILabel class, and 2) MarqueeLabel is not intended to be a "scrolling news ticker" type of control (a UICollectionView would be a better choice for a good number of reasons).

I suggest you try setting up a plain UILabel that uses that string and is sized appropriately, and see if it fails to draw. The easiest way is to left or right align the label frame to the edge of a screen, and allow the label to grow offscreen as needed to fit the string. If the plain UILabel fails to draw as well, there's unfortunately nothing I can do!

**Comment by CrazyDavis** [comment]
ok, finally I set the string max length to avoid the problem, thank you.

**Comment by cbpowell** [comment]
Great! Glad you found a workaround.
