### ISSUE TITLE
marqueeLabel in a UISegmentedControl?

### ISSUE THREAD

**Issue by daviddelmonte** [cbpowell/MarqueeLabel#199]
Is it possible to change the class of the UILabel in a UISegmentedControl to MarqueeLabel?

Thanks!

**Comment by cbpowell** [comment]
It would appear that you could potentially add a MarqueeLabel view as a subview of the segment view, or create a subclass/custom version of UISegmentedControl, but from a quick look at the Apple docs it does not seem like UISegmentedControl has it as a base functionality.

I'm happy to help out where I can with MarqueeLabel issues, but in the future general questions like this are better suited to StackOverflow per the [issue contribution guidelines](https://github.com/cbpowell/MarqueeLabel/blob/master/.github/issue_template.md).

**Comment by daviddelmonte** [comment]
Thanks Charles, sorry about that

**Comment by cbpowell** [comment]
Not a problem! Really I say that because you’ll probably get a better answer there - I’m not too familiar with UISegmentedControl, so I don’t know what can and can’t be done. I do have notifications set up for SO questions tagged with MarqueeLabel so I’ll still see it over there and help out as I can.
