### ISSUE TITLE
Problem with swift4 using Carthage? EXC_BAD_ACCESS (code=2, address=0x11313bc78)

### ISSUE THREAD

**Issue by UzumakiAlfredo** [cbpowell/MarqueeLabel#201]
Hi.
I read the instructions and added MarqueeLabel to my project via carthage, but MarqueeLabel codes are crashing the app on the first line of these codes:

       summaryLabel.type = .continuous  //  <--- here
        summaryLabel.type = .rightLeft
        summaryLabel.speed = .duration(15)
        summaryLabel.animationCurve = .easeInOut
        summaryLabel.fadeLength = 10.0
        summaryLabel.leadingBuffer = 14.0
        summaryLabel.text = "adasnmdasdnajksdakjdakkasdkasnkasdkalsndklaaadada"

 Thanks for this greate library.

**Comment by cbpowell** [comment]
Glad you find it useful!

My guess is you used Interface Builder to create the label, but didn’t change the label custom class to MarqueeLabel in IB. See the info in the read me here: https://github.com/cbpowell/MarqueeLabel/blob/master/README.mdown#storyboards

This error almost always results in a crash, because a plain UILabel instance doesn’t have the .type property.

Let me know if this fixes your issue! If not, could you please post your crash log?

**Comment by UzumakiAlfredo** [comment]
Thanks for your quick reply.

I did know about the  Interface Builder and I changed the UILabel class to MarqueeLabel but did know what to do with inherit section !

what else I can do?

**Comment by UzumakiAlfredo** [comment]
I removed the carthage framework and install it manually and now its working !

Thank you !

**Comment by cbpowell** [comment]
Glad you got it fixed! Might have been a framework import issue then? I don't use Carthage much so I'm not extremely familiar with the common issues.
