### ISSUE TITLE
Cannot find protocol declaration for 'CAAnimationDelegate' 

### ISSUE THREAD

**Issue by pjebs** [cbpowell/MarqueeLabel#210]
I opened up a legacy project that was last touched prob early 2017.

pod file: 
```
platform :ios, '7.0'
...
pod 'MarqueeLabel'
```
It definitely worked back then.

Now it's saying this error: `Cannot find protocol declaration for 'CAAnimationDelegate' `
and pointing to this location:
```
@interface MarqueeLabel : UILabel <CAAnimationDelegate>
```

I think the podspec is not set up correctly for XCode 7.3.2 (ios 7)

**Comment by cbpowell** [comment]
The issue is actually that CAAnimationDelegate _used to be_ and informal protocol (back to like iOS 2.0 or something), and then with iOS 10.0 / Xcode 8.0 it was defined as a true protocol. But the protocol definition is such that it's as if it only existed in the iOS 10 SDK and after, so calling it out in the MarqueeLabel interface causes an error on iOS 7.0.

So I think your options are:
1) Update to and/or use Xcode 8.0, so you can build against a newer SDK while still targeting iOS 7.0. Seems like there are [some](https://forums.developer.apple.com/thread/50410) [ways](https://stackoverflow.com/a/37829427/) to still support iOS 7.0 in Xcode 8.0.
2) Define your own empty `CAAnimationDelegate` protocol, to satisfy the compiler. Haven't tested this myself, so I'm not 100% sure it would work.

Seems like the newer Xcode versions support old iOS versions as build targets, so maybe try Option 1 first if the rest of your build can handle a newer SDK?

**Comment by pjebs** [comment]
Yes. I believe I upgrade min ios from 7 to 9.

**Comment by cbpowell** [comment]
Awesome!
