### ISSUE TITLE
Problem with swift4 ? EXC_BAD_ACCESS (code=2, address=0x1097ceea8)

### ISSUE THREAD

**Issue by amit44405** [cbpowell/MarqueeLabel#221]
Hi.
I read the instructions and added MarqueeLabel to my project, but MarqueeLabel codes are crashing the app on the first line of these codes:

import MarqueeLabel

@IBOutlet weak var artistName: MarqueeLabel!

@IBAction func onClickPrev(_ sender: UIButton) {
        self.artistName.text = artistName 
        self.artistName.speed = .duration(20) //----here
        self.artistName.animationCurve = .easeOut
        self.artistName.type = .continuous
}
        
![screen shot 2018-07-23 at 5 26 18 pm](https://user-images.githubusercontent.com/32383405/43075183-8f66e586-8e9d-11e8-99e1-237c23ff48a9.png)

Thanks for this greate library.

**Comment by cbpowell** [comment]
Glad you find it useful!

Did you change the label custom class to MarqueeLabel in Storyboards? This crash typically happens when the object you're referencing as a MarqueeLabel is still the default UILabel, which doesn't have the `.speed` variable. See the info in the read me here: https://github.com/cbpowell/MarqueeLabel/blob/master/README.mdown#storyboards

This error almost always results in a crash, because a plain UILabel instance doesn’t have the .type property.

Let me know if this fixes your issue! If not, could you please post your crash log?

**Comment by cbpowell** [comment]
Going to assume you got this figured out - please reply back if not!
