### ISSUE TITLE
short string not centered

### ISSUE THREAD

**Issue by appsird** [cbpowell/MarqueeLabel#231]
hello,

Thanks for your contribution with marquee, nicely done.

This issue was logged prior under "Would be possible to have a centered label when the text is not bigger" back in 2012. Using the latest 4.2 release, on the latest 12.1.4 iOS release on iPhone8, I have a text field which is 10 units border on left and right. When a string is less than the Marquee label size, the string is 'almost' centered, though is shifted a bit to the right 2-3 characters or so. I have double checked constraints on the label, and all looks correct. When using large strings, the string scrolls as it should, and one does not notice an alignment anomaly.

I'm using the below settings. I have also shortened the string on your included example so as not to scroll, and notice similar effect. would appreciate any advice on how to avoid this issue.

Brian

___

        let textAttributes = [NSAttributedString.Key.font: UIFont.preferredFont(forTextStyle: UIFont.TextStyle.title1),
                              NSAttributedString.Key.foregroundColor: UIColor.white]
        let textString = NSMutableAttributedString(string: playerState.track.name, attributes: textAttributes)
        trackLabel.attributedText = textString
        trackLabel.textAlignment = .center
    
        trackLabel.type = .continuous
        trackLabel.lineBreakMode = .byTruncatingHead
        trackLabel.speed = .duration(8.0)
        trackLabel.fadeLength = 15.0
        trackLabel.leadingBuffer = 40.0

**Comment by cbpowell** [comment]
Hi - glad you find it useful! Sorry for the slow reply, been on a multi-week vacation.

I see what you mean, but its essentially due to the `leadingBuffer` value so I'm not sure what the best approach would be. When you set a `leadingBuffer`, that is always respected including when the label is short enough to be non-scrolling. The idea behind that is that you can set a leading buffer to left-align multiple labels, so I suppose when the alignment is set to center and the text is short that leading buffer should be ignored?

That should be doable, but I'll have to think about it for the various cases like right-aligned and right-to-left languages.

**Comment by cbpowell** [comment]
I think what I'm going to do is leave the existing functionality as-is, but update some of the documentation to note that the `leadingBuffer` value will affect the alignment position of the text when the label is short and does not require scrolling. In the case of using `.center` alignment, the `leadingBuffer` value has the effect of shifting the center alignment X position to the right (for left-to-right languages) by 1/2 of the `leadingBuffer`. This is true regardless of the text length, although varying text lengths will obviously make the left edge of the text fall in a different spot.

Here's a rough ASCII drawing. The `frame` value of MarqueeLabel is the outer box, but the sublabel is offset to the right by the leading buffer, so the text center alignment point shifts right as well.
````
+------------+------------------------------------------+
|  leading   |                 (sublabel)               |
|  buffer    |                text string               |
|            |                                          |
+------------+-------------+-------+--------------------+
                           ^       ^
                           |       |
                           |       |
                           |       + center align point
                           |
                           + true center of frame
````

My thought process is that changing the functionality to make text center over the "true" center point of the frame would limit the flexibility to use the leading buffer. If someone wanted to have additional space to the left where the text is visible while scrolling, they have to use the `leadingBuffer` to do so - this does shift the center align point, but you can adjust the frame position to predictably account for that and align it to other content or labels.

If you're looking to add a buffer between the text loops, that's what the `trailingBuffer` value is intended for - it expands that distance but has no effect on text positioning otherwise.

**Comment by komsann** [comment]
Hi I face the same issue, what do you think if SDK can provide a flag to check if text reach to scroll or not ? So in this case we can check let leading = textLabel.isReachToScroll ? xx : xx
