### ISSUE TITLE
Control number of times label scrolls

### ISSUE THREAD

**Issue by sbrioux** [cbpowell/MarqueeLabel#232]
### Usage Details
  - Language: Swift
  - Platform: iPhone
  

### Expected Behavior

Scrolling to stop after a defined number of iterations
### Actual Behavior

Scrolling won't stop

Here is my custom class:
```swift
class CustomMarqueeLabel: MarqueeLabel {
    var maxNumOfScrolls: Int?

    var currentNumOfScrolls = 0

    override func labelReturnedToHome(_ finished: Bool) {
        super.labelReturnedToHome(finished)
        currentNumOfScrolls += 1

        if let maxScrolls = self.maxNumOfScrolls, currentNumOfScrolls >= maxScrolls {
            self.shutdownLabel()
        }
    }
}
```

Setup:
```swift
    let titleLabel: CustomMarqueeLabel = {
        let lbl = CustomMarqueeLabel()
        lbl.type = .continuous
        lbl.textColor = .white
        lbl.font = .systemFontRegular(points: 16)
        lbl.trailingBuffer = UIScreen.main.bounds.width
        lbl.animationDelay = 2
        lbl.textAlignment = .center
        lbl.fadeLength = 10
        lbl.maxNumOfScrolls = 3
        return lbl
    }()
```

This CustomMarqueeLabel is currently contained inside a UITableViewCell.  Calls to shutdownLabel() seem to have no effect at all.

Have I missed something?

**Comment by cbpowell** [comment]
If the label is moving offscreen due to UITableView scrolling, that would explain it - is that the case?

If so, and you wanted the label scroll count to be retained when the table view is scrolled and that cell goes offscreen, I'm thinking you would need to keep track of the per-cell `currentNumOfScrolls` value in your datasource so that it can be reapplied when the cell is scrolled back onscreen.

If not, you might still be right that being in a UITableViewCell affects it and we'll have to dig a little more to figure out why.

Side note - I tried your subclass and initially I had trouble getting it to even start scrolling when used as a stand-alone label, because `labelReturnedToHome` can be called multiple times without a true animation occurring and that increments your scroll count. Things like `didMoveToWindow` and repeated `layoutSubview` calls trigger the scroll start, but the animation can then end immediately if the view isn't ready yet. Unfortunately I don't see a way for MarqueeLabel to tell the difference between a scroll animation that is ended prematurely for those reasons vs. when it's interrupted by something else. A setting to disable auto-scrolling could be a workaround, though.

**Comment by sbrioux** [comment]
Thanks for the reply.

The label isn't scrolling off screen and the counting seems to work from log statements printing out the counts.  The problems seem to be trying to make the scrolling **stop**.  The calls to `self.shutdownLabel()` seem to do nothing.

**Comment by cbpowell** [comment]
Didn't get a chance to get back to this until now, but it appears to work for me just in a regular, non-tableview setup. So I'm guessing it might be tableview related?

Just to double check, I'm assuming you have verified with a breakpoint that the `self.shutdownLabel()` function is being called when you expect? (i.e. after 3 scrolls)

Beyond that, I may need you to dig a little further into the MarqueeLabel and assign some breakpoints inside the `shutdownLabel` and `returnLabelToHome` functions to see where things are falling apart. The logic isn't complex at all, so I'm wondering if a reference is getting lost somehow due to tableview containment?

**Comment by cbpowell** [comment]
Also it just occurred to me after posting the above - it's possible `shutdownLabel` is working as intended but something _else_ is triggering the scroll to start again. If you verify that `shutdownLabel` appears to be working, try throwing breakpoint in the `scroll` function (near the start is fine) and see what's in the call tree.

For example, here's what the `scroll` call tree looks like when the label is initially triggered to scroll due to being added to the window. You'd see something similar if the text was changed, for any other layout/sizing parameter being changed that re-triggers scrolling:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/593953/54493483-d1441780-488d-11e9-830b-df5b8ed4097b.png">

Whereas if scrolling is continuing because it's simply looping the animation again, you'd see this. Note the `animationDidStop` callback in the tree:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/593953/54493511-22eca200-488e-11e9-8c57-6d0449fdfd24.png">

If the `shutdownLabel` function is failing to work, you would see the latter because the animation will just continue to loop. But if say `layoutSubviews` is getting called at about the same time, or you're changing the text value, the scrolling animation will be triggered again.

**Comment by daviddelmonte** [comment]
Charles, can we request this as an additional function? I'd rather not subclass ML and roll my own.

**Comment by cbpowell** [comment]
@daviddelmonte well I'm hesitant to include it as a base feature considering the fact that we have an issue already! But in general I feel like it's something that a subclass or the view controller could handle with more reliability for a given particular use case.

Primarily because of the things I note in [this comment above](
https://github.com/cbpowell/MarqueeLabel/issues/232#issuecomment-470355379) - sometimes "scrolls" can be accumulated for random reasons so it's hard for MarqueeLabel (which is just a base UIView) to know what's going on the with rest of the system. I would have to make assumptions which maybe wouldn't always be right, and that just adds to configuration bloat and more confusion when things don't work right.

Once we get this sorted out I do plan on adding @sbrioux's subclass to the [Extras Folder](https://github.com/cbpowell/MarqueeLabel/tree/master/Extras) though! Also that's the beauty of subclassing, you get all the base features with new stuff added!

**Comment by sbrioux** [comment]
So I can confirm that a breakpoint set inside the if statement will be hit.  But shutdown label didn't seem to have any effect on the label scrolling.
```swift
        if let maxScrolls = self.maxNumOfScrolls, currentNumOfScrolls >= maxScrolls {
            self.shutdownLabel()
        }
```

I did end up getting this working but had to use a mixture of thing.  1st I instantiated the label to have a `holdScrolling` value of `true`.  I then had to create a method in the custom class that does the following:
```swift
    func restartScrolling() {
        // reset the scroll count back to 0
        self.currentNumOfScrolls = 0
        // If the holdScrolling is already false then setting it to false again will not cause scrolling to start.. trigger it
        if !self.holdScrolling {
            self.triggerScrollStart()
        }
        self.holdScrolling = false
    }
```

Then lastly I updated the override method to the following:

```swift
    override func labelReturnedToHome(_ finished: Bool) {
        super.labelReturnedToHome(finished)

        // If max scrolls isn't set then we don't need to stop the scrolling
        guard self.maxNumOfScrolls > 0 else { return }

        // Increment scroll count
        self.currentNumOfScrolls += 1

        // If the current number of scrolls is greater then or equal to max stop scrolling
        if self.currentNumOfScrolls > self.maxNumOfScrolls {
            super.holdScrolling = true
        }
        os_log("%@ text : [%@] current :[%d] max: [%d]", log: .default, type: .debug, #function, self.text ?? "",
               currentNumOfScrolls, self.maxNumOfScrolls)
    }
```

Also `maxNumberOfScrolls` is no longer an option and just an Int now with default value of 0

**Comment by cbpowell** [comment]
I think we can consider this one closed/solved now? Just cleaning up some of the long-time issues. Let me know if anyone disagrees!
