### ISSUE TITLE
Can not build MarqueeLabel using Carthage

### ISSUE THREAD

**Issue by Tchuba** [cbpowell/MarqueeLabel#240]
When using carthage update MarqueeLabel with version  4.0.0 for a tvOS target, I get the following error:

~ ~ ~
A shell task (/usr/bin/xcrun xcodebuild -project /Users/petrkubista/work/Code/RFE/RFE_News_iOS_New/Carthage/tvOS/Carthage/Checkouts/MarqueeLabel/MarqueeLabelSwift/MarqueeLabelSwift.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
xcodebuild: error: Unable to read project 'MarqueeLabelSwift.xcodeproj' from folder '/Users/petrkubista/work/Code/RFE/RFE_News_iOS_New/Carthage/tvOS/Carthage/Checkouts/MarqueeLabel/MarqueeLabelSwift'.
	Reason: Project /Users/petrkubista/work/Code/RFE/RFE_News_iOS_New/Carthage/tvOS/Carthage/Checkouts/MarqueeLabel/MarqueeLabelSwift/MarqueeLabelSwift.xcodeproj cannot be opened because it is missing its project.pbxproj file.
~ ~ ~

The same error was already reported here:
https://github.com/cbpowell/MarqueeLabel/issues/136

**Comment by cbpowell** [comment]
I think you need to clear out your Carthage build folder. Version 4.0.0 eliminated the `MarqueeLabelSwift` project from this repo, now it's just `MarqueeLabel` (because the ObjC code was split into a deprecated repo).

I was messing with my Carthage test project earlier and I think I ran into this, and clearing the Build folder was part of what fixed it. I would do the following:

1. Delete the MarqueeLabel build files from your project Carthage folder.
2. Run `carthage update` or your personal equivalent.
3. Reconfigure your project (per the Carthage instructions) to use the `MarqueeLabel` framework, instead of the now-legacy `MarqueeLabelSwift` framework.
