### ISSUE TITLE
i'm using collectionView to for displaying data, and i want one of the label to make it marquee can anyone help me how to set the property?

### ISSUE THREAD

**Issue by MeetThanki** [cbpowell/MarqueeLabel#253]
### Usage Details
  - Language: 
  - Platform: 
  - iOS Version:  
  

### Steps to Reproduce the Problem

  1.
  1.
  1.

**Comment by cbpowell** [comment]
Hi @MeetThanki - please take a look at the example project with a UITableView, it should be pretty similar!

Specifically these lines here: https://github.com/cbpowell/MarqueeLabel/blob/53f333932aaf7cce7ce002ed5b21ccf249e23db0/MarqueeLabel/MarqueeLabelTableViewController.swift#L66-L72

When that cell is tapped (selected), it gets a reference to that cell as a MLCell (instead of just the basic UITableViewCell) which has a `label` property for the MarqueeLabel instance in that particular cell.

It then sets the `labelize` property of the MarqueeLabel to `false` to begin the scroll animation. Note that at cell creation the `labelize` property is set to `true` ([here](https://github.com/cbpowell/MarqueeLabel/blob/53f333932aaf7cce7ce002ed5b21ccf249e23db0/MarqueeLabel/MarqueeLabelTableViewController.swift#L57-L58)), so that all the cells aren't scrolling simultaneously. You may or may not want to do that for your use case.

Hope this helps!
