### ISSUE TITLE
Can't access speed property in Objc

### ISSUE THREAD

**Issue by HermanKayy** [cbpowell/MarqueeLabel#261]
The speed property is not accessible in Objc class. Does this have anything to do with the fact that it's not ibinspectable? Currently using deprecated property `scrollRate`. Any issues with that?

**Comment by HermanKayy** [comment]
Language: Objc
Platform: iOS

**Comment by cbpowell** [comment]
Hmm are you using the Swift library imported for ObjC? I think the problem is the `speed` property requires the type of Swift enum with associated value, which as far as I know isn't provided in the ObjC translation - but I may not be fully up to date on that. If there's a workaround using a custom header file instead of the system generated one I'd be open to that.

Maybe not the best practice, but you're fine using the deprecated properties for now. I have no plans to remove them anytime soon (mostly for this reason).

**Comment by HermanKayy** [comment]
The objc code will be deprecated soon so I think it should be okay as long as the deprecated property will still be around for a while. Thanks for your help!
