### ISSUE TITLE
Immediately display next instance of short text in continuous scroll

### ISSUE THREAD

**Issue by isaranjha** [cbpowell/MarqueeLabel#262]
In continuous scroll with short text, MarqueeLabel waits until there is what I'm guessing enough space to fit the next instance of said text. How can I get the next instance of the text to show immediately after the trailingBuffer like so:

`
|XXXX   XXXX    XX|
`

...versus what is happening now:

```
|XXX   XXXX |
|XX   XXXX  |
|X   XXXX   |
|  XXXX     |
|XXXX   XXXX|
```

**Comment by isaranjha** [comment]
Solved! With `repliLayer?.instanceCount = 20`

**Comment by cbpowell** [comment]
Nice! Glad you found a solution that works.

To answer your question/comment on #173 - correct, as of now you can’t easily have a fade length but also have a zero width buffer between labels without a little custom modification.

[This line](https://github.com/cbpowell/MarqueeLabel/blob/a034b83919cbc272243810cd7bfb9b60d2fccb2c/Sources/MarqueeLabel.swift#L627) forces the label spacing to be the largest of ‘leadingBuffer’, ‘trailingBuffer’, and ‘fadeLength’. I’ll admit it’s been a few years since I set that up, but I recall it’s because at the end of the movement animation, it needs at least that amount of spacing to prevent the other instance of the label from appearing onscreen at an edge. 

Seems like maybe you’re going for more of a “news marquee”, with a continuous scroll of text? MarqueeLabel can be made to kind of do that, but it was designed to emulate the iTunes/Music app labels which are a little different. 

If you want to be able to easily change the text, or just portions of the text, something like an infinite scrolling collection view will be much more flexible in the end!

**Comment by isaranjha** [comment]
I actually was just about to nullify my comment because I found that line and removed the fadeLength from consideration. A stock ticker, actually! It works great for my purposes and I haven't run into any issues yet. One thing I'm struggling with right now though is right as the 'start of the text' fades to the left, as soon as it hits 'home' it flashes out of the fade for a quick second and then back to being faded. What line should I be hunting down to remove that flash so that it passes through 'home' faded the whole time?

**Comment by cbpowell** [comment]
Hmm, does it do that if the layer count is set to 1? Or only when set to 20?

Would seem something with the animation timing is getting affected. You’ll maybe want to play around with setting up a custom scroll sequence. See [around here](https://github.com/cbpowell/MarqueeLabel/blob/a034b83919cbc272243810cd7bfb9b60d2fccb2c/Sources/MarqueeLabel.swift#L650) for the default example, and the [property description here](https://github.com/cbpowell/MarqueeLabel/blob/a034b83919cbc272243810cd7bfb9b60d2fccb2c/Sources/MarqueeLabel.swift#L92).

**Comment by isaranjha** [comment]
It does it even when it's set to 1. Very strange. I tried playing with the animation sequence but it really didn't make any difference. 

I presume it's there because as the label comes to a stop, it should be opaque. But since I'm having it scroll continuously, there's something causing it to animate out of being faded thinking it's about to stop, but it isn't...

**Comment by cbpowell** [comment]
That did make me think of another solution someone applied once I think - don’t set a fade on the MarqueeLabel at all, but then wrap it in another view and apply the fade on that parent view. Useful if you want a permanent edge fade anyway!

**Comment by isaranjha** [comment]
Went with this solution and worked great!
